server:
  port: 8081
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_member?serverTimezone=Asia/Shanghai
    username: train_member
    password: 12306Train@
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: member
  cloud:
    nacos:
      server-addr: 172.17.0.3:8848
logging:
  level:
    com.senvu.train.member.mapper: trace
mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.senvu.train.member.common
  #扫描mapper文件
  mapper-locations: classpath:mapper/*.xml