server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/batch/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:8080"
              - "http://localhost:9001"
              - "http://127.0.0.1:8080"
              - "http://127.0.0.1:9001"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 360000
    nacos:
      server-addr: 172.17.0.3:8848